testkk

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -26,7 +26,7 @@ jobs:
     needs: lint
 
     outputs:
-      CHECK_CODE_RESULT: ''
+      CHECK_CODE_RESULT: ${{ steps.build.outputs.CHECK_CODE_RESULT }}
 
     steps:
       - name: Checkout Code
@@ -42,9 +42,13 @@ jobs:
 
       - name: Build project
         run: |
-          npm run build
-          # Assuming you have some way to capture build result
-          echo "::set-output name=CHECK_CODE_RESULT::Build element"  # Example output
+          npm run build  # ทำการบิลด์โครงการ
+          # ตรวจสอบว่ามีข้อผิดพลาดหรือไม่
+          if [ $? -ne 0 ]; then
+            echo "::error::Build failed"
+            exit 1
+          fi
+          echo "::set-output name=CHECK_CODE_RESULT::Build successful"
 
   push_to_registry:
     name: Push Docker image to Docker Hub
@@ -112,6 +116,9 @@ jobs:
     needs: [lint, build, push_to_registry, get_commit_author_email]
     if: ${{ failure() }}
     steps:
+      - name: Set up Git
+        uses: actions/checkout@v2
+
       - name: Send email on failure
         uses: dawidd6/action-send-mail@v3
         with:
@@ -128,4 +135,3 @@ jobs:
             ${{ needs.get_commit_author_email.outputs.changed_files }}
           to: ${{ needs.get_commit_author_email.outputs.commit_author_email }}
           from: ${{ secrets.GMAIL_USERNAME }}
-
