Update pushlog.yml

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -41,7 +41,17 @@ jobs:
         run: npm install
 
       - name: Build project
-        run: npm run build
+        id: build_step
+        run: |
+          npm run build 2> build_errors.log || true
+          if grep -q "error" build_errors.log; then
+            echo "Check code failed"
+            echo "::set-output name=error_files::$(grep "error" build_errors.log | awk -F: '{print $1}' | sort | uniq | tr '\n' ' ')"
+            exit 1
+          else
+            echo "Check code succeeded"
+            echo "::set-output name=error_files::"
+          fi
 
       - name: Determine check code result
         run: |
@@ -118,18 +128,18 @@ jobs:
     name: Send Notification
     runs-on: ubuntu-latest
     needs: [lint, build, push_to_registry, get_commit_author_email]
-    if: ${{ failure() }}
+    if: ${{ failure() && needs.build.outputs.error_files != '' }}
     steps:
-      - name: Send email on failure
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 587
-          username: ${{ secrets.GMAIL_USERNAME }}
-          password: ${{ secrets.GMAIL_APP_PASSWORD }}
-          subject: ${{ github.job }} job of ${{ github.repository }}
-          body: |
-            The following files were committed and pushed:
-            ${{ needs.get_commit_author_email.outputs.changed_files }}
-          to: ${{ needs.get_commit_author_email.outputs.commit_author_email }}
-          from: ${{ secrets.GMAIL_USERNAME }}
+    - name: Send email on failure
+      uses: dawidd6/action-send-mail@v3
+      with:
+        server_address: smtp.gmail.com
+        server_port: 587
+        username: ${{ secrets.GMAIL_USERNAME }}
+        password: ${{ secrets.GMAIL_APP_PASSWORD }}
+        subject: ${{ github.job }} job of ${{ github.repository }} 
+        body: |
+          The following files caused errors during the build:
+          ${{ needs.build.outputs.error_files }}
+        to: ${{ needs.get_commit_author_email.outputs.commit_author_email }}
+        from: ${{ secrets.GMAIL_USERNAME }}
