test12

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -97,10 +97,15 @@ jobs:
 
       - name: Create New Branch with Commit Message
         env:
-           GH_PAT: ${{ secrets.GH_PAT }}
+          GH_PAT: ${{ secrets.GH_PAT }}
         run: |
-            git config user.name dornrock123
-            git config user.email krisd3214@gmail.com
+            # Get the author information from the latest commit
+            COMMIT_AUTHOR_NAME=$(git log -1 --pretty=%an)
+            COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
+
+            # Set the git config to use the author's info
+            git config user.name "$COMMIT_AUTHOR_NAME"
+            git config user.email "$COMMIT_AUTHOR_EMAIL"
 
             FULL_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
 
@@ -131,74 +136,69 @@ jobs:
           --user "dornrock:1147d17fc8ec8e23ed131270370d186bf6"
 
   send_failure_notification:
-        name: Send Failure Notification
-        runs-on: ubuntu-latest
-        needs: build
-        if: ${{ failure() }}
-        steps:
-          - name: Checkout Code
-            uses: actions/checkout@v3
-            with:
-              fetch-depth: 0  # Fetch all history
+    name: Send Failure Notification
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ failure() }}
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0  # Fetch all history
 
-          - name: Download Error Files
-            uses: actions/download-artifact@v3
-            with:
-              name: error-files
+      - name: Download Error Files
+        uses: actions/download-artifact@v3
+        with:
+          name: error-files
 
-          - name: Get Error Log and Commit Info
-            id: error_info
-            run: |
-              git config --global user.email "krisd3214@gmail.com"
-              git config --global user.name "dornrock123"
+      - name: Get Error Log and Commit Info
+        id: error_info
+        run: |
+          # Get the author information from the latest commit
+          COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae)
 
-              commit_author_email=$(git log -1 --format='%ae')
-              echo "Raw commit email: $commit_author_email"
+          if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%b | grep -oP '(?<=Signed-off-by: ).*(?= <)')
+          fi
 
-              if [[ "$commit_author_email" == *"@users.noreply.github.com" ]]; then
-                commit_author_email=$(git log -1 --format='%b' | grep -oP '(?<=Signed-off-by: ).*(?= <)')
-                echo "Email from commit message: $commit_author_email"
-              fi
+          if [[ -z "$COMMIT_AUTHOR_EMAIL" || "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL="krisd3214@gmail.com"
+          fi
 
-              if [[ -z "$commit_author_email" || "$commit_author_email" == *"@users.noreply.github.com" ]]; then
-                commit_author_email="krisd3214@gmail.com"
-                echo "Using default email: $commit_author_email"
-              fi
+          changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
 
-              changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
+          error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
+          echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
 
-              error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
-              echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
+          non_error_files=""
+          for file in $changed_files; do
+            if ! grep -q "$file" build_errors.log; then
+              non_error_files+="$file "
+            fi
+          done
 
-              non_error_files=""
-              for file in $changed_files; do
-                if ! grep -q "$file" build_errors.log; then
-                  non_error_files+="$file "
-                fi
-              done
+          echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
+          echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
 
-              echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
-              echo "commit_author_email=$commit_author_email" >> $GITHUB_OUTPUT
+      - name: Send email on failure
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.GMAIL_USERNAME }}
+          password: ${{ secrets.GMAIL_APP_PASSWORD }}
+          subject: "Build failure for ${{ github.repository }}"
+          body: |
+            Build failed for commit: ${{ github.sha }}
 
-          - name: Send email on failure
-            uses: dawidd6/action-send-mail@v3
-            with:
-              server_address: smtp.gmail.com
-              server_port: 587
-              username: ${{ secrets.GMAIL_USERNAME }}
-              password: ${{ secrets.GMAIL_APP_PASSWORD }}
-              subject: "Build failure for ${{ github.repository }}"
-              body: |
-                Build failed for commit: ${{ github.sha }}
+            Files with errors:
+            ${{ steps.error_info.outputs.error_paths }}
 
-                Files with errors:
-                ${{ steps.error_info.outputs.error_paths }}
+            Files changed: ${{ steps.error_info.outputs.non_error_files }}
 
-                Files changed: ${{ steps.error_info.outputs.non_error_files }}
-
-              to: ${{ steps.error_info.outputs.commit_author_email }}
-              from: ${{ secrets.GMAIL_USERNAME }}
-              attachments: build_errors.log
+          to: ${{ steps.error_info.outputs.commit_author_email }}
+          from: ${{ secrets.GMAIL_USERNAME }}
+          attachments: build_errors.log
 
   send_success_notification:
     name: Send Success Notification
@@ -206,44 +206,39 @@ jobs:
     needs: [lint, build, push_to_registry]
     if: ${{ success() }}
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v3
-      with:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+        with:
           fetch-depth: 0  # Fetch all history
 
-    - name: Get Commit Info
-      id: commit_info
-      run: |
-          git config --global user.email "krisd3214@gmail.com"
-          git config --global user.name "dornrock123"
+      - name: Get Commit Info
+        id: commit_info
+        run: |
+          # Get the author information from the latest commit
+          COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%ae')
 
-          commit_author_email=$(git log -1 --format='%ae')
-          echo "Raw commit email: $commit_author_email"
-
-          if [[ "$commit_author_email" == *"@users.noreply.github.com" ]]; then
-            commit_author_email=$(git log -1 --format='%b' | grep -oP '(?<=Signed-off-by: ).*(?= <)')
-            echo "Email from commit message: $commit_author_email"
+          if [[ "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL=$(git log -1 --format='%b' | grep -oP '(?<=Signed-off-by: ).*(?= <)')
           fi
 
-          if [[ -z "$commit_author_email" || "$commit_author_email" == *"@users.noreply.github.com" ]]; then
-            commit_author_email="krisd3214@gmail.com"
-            echo "Using default email: $commit_author_email"
+          if [[ -z "$COMMIT_AUTHOR_EMAIL" || "$COMMIT_AUTHOR_EMAIL" == *"@users.noreply.github.com" ]]; then
+            COMMIT_AUTHOR_EMAIL="krisd3214@gmail.com"
           fi
 
           changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
-          echo "commit_author_email=$commit_author_email" >> $GITHUB_OUTPUT
+          echo "commit_author_email=$COMMIT_AUTHOR_EMAIL" >> $GITHUB_OUTPUT
           echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
 
-    - name: Send email on success
-      uses: dawidd6/action-send-mail@v3
-      with:
+      - name: Send email on success
+        uses: dawidd6/action-send-mail@v3
+        with:
           server_address: smtp.gmail.com
           server_port: 587
           username: ${{ secrets.GMAIL_USERNAME }}
           password: ${{ secrets.GMAIL_APP_PASSWORD }}
-          subject: "Build success for ${{ github.repository }}"
+          subject: "Build Success for ${{ github.repository }}"
           body: |
-            Build successful for commit: ${{ github.sha }}
+            Build succeeded for commit: ${{ github.sha }}
 
             Files changed: ${{ steps.commit_info.outputs.changed_files }}
 
