test0

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -41,7 +41,9 @@ jobs:
         run: npm install
 
       - name: Build project
-        run: npm run build
+        id: build_step
+        run: |
+          npm run build 2> build_errors.log || true
 
       - name: Determine check code result
         id: determine_check_code_result
@@ -53,10 +55,8 @@ jobs:
             exit 1
           else
             echo "Check code succeeded"
-            echo "::set-env name=CHECK_CODE_RESULT::success"
-          else
-            echo "Check code failed"
-            echo "::set-env name=CHECK_CODE_RESULT::failure"
+            echo "::set-output name=error_files::"
+          fi
 
   push_to_registry:
     name: Push Docker image to Docker Hub
@@ -97,6 +97,7 @@ jobs:
           NEW_BRANCH_NAME="log-$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-' | tr '[:punct:]' '-')"
           git checkout -b $NEW_BRANCH_NAME
           git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
+
   get_commit_author_email:
     name: Get Commit Author Email
     runs-on: ubuntu-latest
@@ -116,11 +117,12 @@ jobs:
           CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | tr '\n' ' ')
           echo "::set-output name=commit_author_email::${AUTHOR_EMAIL}"
           echo "::set-output name=changed_files::${CHANGED_FILES}"
+
   send_notification:
     name: Send Notification
     runs-on: ubuntu-latest
     needs: [lint, build, push_to_registry, get_commit_author_email]
-    if: ${{ failure() }}
+    if: ${{ needs.build.outputs.error_files != '' }}
     steps:
       - name: Send email on failure
         uses: dawidd6/action-send-mail@v3
@@ -131,7 +133,7 @@ jobs:
           password: ${{ secrets.GMAIL_APP_PASSWORD }}
           subject: ${{ github.job }} job of ${{ github.repository }}
           body: |
-            The following files were committed and pushed:
-            ${{ needs.get_commit_author_email.outputs.changed_files }}
+            The following files caused errors during the build:
+            ${{ needs.build.outputs.error_files }}
           to: ${{ needs.get_commit_author_email.outputs.commit_author_email }}
           from: ${{ secrets.GMAIL_USERNAME }}
