testss

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -1,4 +1,3 @@
-
 name: CI Pipeline
 
 on:
@@ -54,6 +53,76 @@ jobs:
           name: error-files
           path: build_errors.log
 
+            # Run API Job
+  run-api:
+    name: Run API
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout API repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-API
+          ref: ${{ github.event.inputs.api_branch || 'main' }}
+          token: ${{ secrets.GH_PAT }}
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          distribution: "adopt"
+          java-version: "17"
+
+      - name: Build and Run Spring Boot API
+        run: |
+          mvn clean install
+          nohup mvn spring-boot:run > /dev/null 2>&1 &
+
+  # Run Web and Playwright Tests Job
+  run-web-and-test:
+    name: Run Web and Playwright Tests
+    runs-on: ubuntu-latest
+    needs: run-api
+
+    steps:
+      - name: Checkout Web repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-Web
+          token: ${{ secrets.GH_PAT }}
+          ref: ${{ github.event.inputs.web_branch || 'main' }}
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "16.20.2"
+
+      - name: Set npm registry
+        run: npm config set registry https://registry.npmjs.org/
+
+      - name: Install dependencies
+        run: npm install --force
+
+      - name: Start the app
+        run: |
+          npm start &
+          npx wait-on http://localhost:4200
+        env:
+          PORT: 4200
+
+      - name: Install Playwright
+        run: npx playwright install
+
+      - name: Run Playwright tests
+        id: run-tests
+        run: |
+          npx playwright test president/E2E-Script --output=results.json || exit 1
+          if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
+            echo "Tests failed."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
+
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
@@ -83,50 +152,50 @@ jobs:
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
 
-  # zap_scan:
-  #   name: Run ZAP Scan
-  #   runs-on: ubuntu-latest
-  #   needs: push_to_registry
-  #   steps:
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v3
+  zap_scan:
+    name: Run ZAP Scan
+    runs-on: ubuntu-latest
+    needs: push_to_registry
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
 
-  #     - name: List files to verify dockerfile location
-  #       run: |
-  #         ls -la
-  #         ls -la dockerfile
+      - name: List files to verify dockerfile location
+        run: |
+          ls -la
+          ls -la dockerfile
 
-  #     - name: Build ZAP Docker Image
-  #       run: |
-  #         docker pull lefisius/dockerbuild:main
-  #         docker run -d --name zap -p 8080:8080 lefisius/dockerbuild:main
+      - name: Build ZAP Docker Image
+        run: |
+          docker pull lefisius/dockerbuild:main
+          docker run -d --name zap -p 8080:8080 lefisius/dockerbuild:main
 
-  #     - name: Run ZAP Container
-  #       run: |
-  #         docker run -d --name zap -p 8080:8080 zap-scan-image
-  #         sleep 60
+      - name: Run ZAP Container
+        run: |
+          docker run -d --name zap -p 8080:8080 zap-scan-image
+          sleep 60
 
-  #     - name: Start ZAP Scan
-  #       run: |
-  #         docker exec zap zap-baseline.py -t http://localhost:4200/ -r zap_report.html
-  #       env:
-  #         ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
+      - name: Start ZAP Scan
+        run: |
+          docker exec zap zap-baseline.py -t http://localhost:4200/ -r zap_report.html
+        env:
+          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
 
-  #     - name: Upload ZAP Report
-  #       uses: actions/upload-artifact@v3
-  #       with:
-  #         name: zap-report
-  #         path: zap_report.html
+      - name: Upload ZAP Report
+        uses: actions/upload-artifact@v3
+        with:
+          name: zap-report
+          path: zap_report.html
 
-  # trigger_jenkins:
-  #   name: Trigger Jenkins Job
-  #   runs-on: ubuntu-latest
-  #   needs: zap_scan
-  #   steps:
-  #     - name: Trigger Jenkins Job
-  #       run: |
-  #         curl -X POST "https://9569-61-7-146-25.ngrok-free.app/job/testpipe/build" \
-  #         --user "user:11b20d5f21817203f0fb4db12e13b2402e"
+  trigger_jenkins:
+    name: Trigger Jenkins Job
+    runs-on: ubuntu-latest
+    needs: zap_scan
+    steps:
+      - name: Trigger Jenkins Job
+        run: |
+          curl -X POST "https://9569-61-7-146-25.ngrok-free.app/job/testpipe/build" \
+          --user "user:11b20d5f21817203f0fb4db12e13b2402e"
 
   get_commit_author_email:
     name: Get Commit Author Email
@@ -151,7 +220,7 @@ jobs:
   send_failure_notification:
     name: Send Failure Notification
     runs-on: ubuntu-latest
-    needs: [ lint, build, push_to_registry]
+    needs: [ lint, build, push_to_registry, zap_scan, trigger_jenkins]
     if: ${{ failure() }}
     steps:
       - name: Checkout Code
@@ -217,7 +286,7 @@ jobs:
   send_success_notification:
     name: Send Success Notification
     runs-on: ubuntu-latest
-    needs: [ lint, build, push_to_registry]
+    needs: [ lint, build, push_to_registry, zap_scan, trigger_jenkins]
     if: ${{ always() }}
     steps:
       - name: Checkout Code
