do flow

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -1,4 +1,4 @@
-name: CI with Docker, Jenkins, and Notifications
+name: CI Pipeline
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -11,33 +11,56 @@ on:
   pull_request:
     branches:
       - main
+  workflow_dispatch:
+    inputs:
+      api_branch:
+        description: 'API branch to checkout'
+        required: true
+        default: 'main'
+      web_branch:
+        description: 'Web branch to checkout'
+        required: true
+        default: 'main'
 
 jobs:
-  lint:
-    name: Lint Code Base
-    runs-on: ubuntu-latest
-    concurrency:
-      group: lint-${{ github.ref }}
-      cancel-in-progress: false
+  # dependabot:
+  #   name: Dependabot Updates
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v3
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+  #     - name: Set up Dependabot Configuration
+  #       run: |
+  #         echo "version: 2" > .github/dependabot.yml
+  #         echo "updates:" >> .github/dependabot.yml
+  #         echo "  - package-ecosystem: \"npm\"" >> .github/dependabot.yml
+  #         echo "    directory: \"/\"" >> .github/dependabot.yml
+  #         echo "    schedule:" >> .github/dependabot.yml
+  #         echo "      interval: \"monthly\"" >> .github/dependabot.yml
+  #         echo "    open-pull-requests-limit: 10" >> .github/dependabot.yml
+  #         echo "Dependabot configuration created"
+  #       shell: bash
+  #       continue-on-error: true
 
-      - name: Run Super-Linter
-        uses: github/super-linter@v4
-        env:
-          VALIDATE_ALL_CODEBASE: false
-          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
+  # lint:
+  #   name: Lint Code Base
+  #   runs-on: ubuntu-latest
+  #   needs: dependabot
+  #   steps:
+  #     - name: Checkout Code
+  #       uses: actions/checkout@v3
+
+  #     - name: Run Super-Linter
+  #       uses: github/super-linter@v4
+  #       env:
+  #         VALIDATE_ALL_CODEBASE: false
+  #         GITHUB_TOKEN: ${{ secrets.GH_PAT }}
 
   build:
     name: Build Project
     runs-on: ubuntu-latest
-    needs: lint
-    concurrency:
-      group: build-${{ github.ref }}
-      cancel-in-progress: false
-
+    # needs: lint
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -45,29 +68,109 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: '18'
+          node-version: "16.20.2"
 
       - name: Install dependencies
-        run: npm install
+        run: npm install --legacy-peer-deps
 
       - name: Build Project
         id: build
         run: |
-          npm run build 2> build_errors.log
+          npm run build 2> build_errors.log || true
           exit_code=$?
-          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_OUTPUT
+          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
+          exit $exit_code
 
       - name: Upload Error Files
-        if: ${{ steps.build.outputs.error_files_present == 'true' || always() }}
+        if: ${{ env.error_files_present == 'true' || always() }}
         uses: actions/upload-artifact@v3
         with:
           name: error-files
           path: build_errors.log
 
+  # Run API Job
+  run-api:
+    name: Run API
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout API repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-API
+          ref: ${{ github.event.inputs.api_branch || 'main' }}
+          token: ${{ secrets.GH_PAT }}
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v2
+        with:
+          distribution: 'adopt'
+          java-version: '17'
+
+      - name: Build and Run Spring Boot API
+        run: |
+          mvn clean install
+          nohup mvn spring-boot:run > /dev/null 2>&1 &
+
+  # Run Web and Playwright Tests Job
+  run-web-and-test:
+    name: Run Web and Playwright Tests
+    runs-on: ubuntu-latest
+    needs: run-api
+
+    steps:
+      - name: Checkout Web repository
+        uses: actions/checkout@v3
+        with:
+          repository: Theerapat-dev/PresidentDemo-Web
+          token: ${{ secrets.GH_PAT }}
+          ref: ${{ github.event.inputs.web_branch || 'main' }}
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: '16'
+
+      - name: Set npm registry
+        run: npm config set registry https://registry.npmjs.org/
+
+      - name: Install dependencies
+        run: npm install --force
+
+      - name: Start the app
+        run: |
+          npm start &
+          npx wait-on http://localhost:4200
+        env:
+          PORT: 4200
+
+      - name: Install Playwright
+        run: npx playwright install
+
+      - name: Run Playwright tests
+        id: run-tests
+        run: |
+          npx playwright test --output=results.json || exit 1
+          if jq -e '.[] | select(.status == "failed")' results.json > /dev/null; then
+            echo "Tests failed."
+            exit 1
+          else
+            echo "Tests passed."
+          fi
+
+      - name: Upload test results
+        if: always()
+        uses: actions/upload-artifact@v3
+        with:
+          name: playwright-results
+          path: results.json
+
   push_to_registry:
     name: Push Docker image to Docker Hub
     runs-on: ubuntu-latest
+    needs: run-web-and-test
     needs: build
+    needs: run-api
     concurrency:
       group: push-to-registry-${{ github.ref }}
       cancel-in-progress: false
@@ -86,7 +189,7 @@ jobs:
         id: meta
         uses: docker/metadata-action@v4
         with:
-          images: krisneonploy/dockerbuild
+          images: lefisius/dockerbuild
 
       - name: Build and push Docker image
         uses: docker/build-push-action@v4
@@ -140,10 +243,56 @@ jobs:
             git checkout -b $NEW_BRANCH_NAME
             git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
 
-  trigger_jenkins_job:
-    name: Trigger Jenkins Job
+  ZAP_Full_Scan:
     runs-on: ubuntu-latest
     needs: push_to_registry
+    name: ZAP Full Scan Webapplication
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: master
+
+      - name: ZAP Scan
+        uses: zaproxy/action-full-scan@v0.11.0
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
+          target: "https://e628d8c0cdb8d05495ea252b22096c1f.serveo.net/"
+          cmd_options: "-a"
+
+  ZAP_API_Scan:
+    runs-on: ubuntu-latest
+    needs: push_to_registry
+    name: ZAP_API_Scan
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          ref: master
+
+      - name: ZAP Scan
+        uses: zaproxy/action-api-scan@v0.8.0
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
+          format: openapi
+          target: "https://e628d8c0cdb8d05495ea252b22096c1f.serveo.net/"
+          cmd_options: "-a"
+
+      - name: Upload ZAP Scan Report
+        uses: actions/upload-artifact@v3
+        with:
+          name: ZAP_API_Scan
+          path: |
+            report_json.json
+            report_md.md
+            report_html.html
+
+  trigger_jenkins:
+    name: Trigger Jenkins Job
+    runs-on: ubuntu-latest
+    needs: [ZAP_Full_Scan, ZAP_API_Scan]
     if: github.ref == 'refs/heads/main'
     concurrency:
       group: trigger-jenkins-job-${{ github.ref }}
@@ -156,62 +305,73 @@ jobs:
       - name: Trigger Jenkins Job
         id: trigger_jenkins
         run: |
-          response=$(curl -X POST "https://1412-61-7-146-25.ngrok-free.app/job/dornny/build" \
-          --user "dornrock:1147d17fc8ec8e23ed131270370d186bf6")
+          response=$(curl -X POST "https://7bfe77155e1704b6bda5b9043029c178.serveo.net/job/testpipe/build" \
+          --user "user:11b20d5f21817203f0fb4db12e13b2402e")
           echo "Triggered Jenkins Job"
 
       - name: Wait for Jenkins Job to Complete
         run: |
-            job_status="null"
-            max_attempts=20
-            attempt=0
-            while [ "$job_status" != "SUCCESS" ] && [ $attempt -lt $max_attempts ]; do
-              sleep 15
-              attempt=$((attempt+1))
-              response=$(curl -s -w "%{http_code}" "https://1412-61-7-146-25.ngrok-free.app/job/dornny/lastBuild/api/json" \
-                --user "dornrock:1147d17fc8ec8e23ed131270370d186bf6")
-              http_code=${response: -3}
-              body=${response:0:${#response}-3}
+          job_status="null"
+          max_attempts=20
+          attempt=0
+          while [ "$job_status" != "SUCCESS" ] && [ $attempt -lt $max_attempts ]; do
+            sleep 15
+            attempt=$((attempt+1))
+            response=$(curl -s -w "%{http_code}" "https://7bfe77155e1704b6bda5b9043029c178.serveo.net/job/testpipe/lastBuild/api/json" \
+              --user "user:11b20d5f21817203f0fb4db12e13b2402e")
+            http_code=${response: -3}
+            body=${response:0:${#response}-3}
 
-              echo "HTTP Response Code: $http_code"
+            echo "HTTP Response Code: $http_code"
 
-              if [ "$http_code" -ne 200 ]; then
-                echo "Error fetching Jenkins job status. HTTP Response Code: $http_code"
-                echo "Response body: $body"
-                if [ $attempt -eq $max_attempts ]; then
-                  echo "Max attempts reached. Exiting."
-                  exit 1
-                fi
-                continue
-              fi
-
-              if ! job_status=$(echo "$body" | jq -r '.result'); then
-                echo "Error parsing JSON response. Raw response:"
-                echo "$body"
-                if [ $attempt -eq $max_attempts ]; then
-                  echo "Max attempts reached. Exiting."
-                  exit 1
-                fi
-                continue
-              fi
-
-              echo "Current Job Status: $job_status"
-
-              if [ "$job_status" = "FAILURE" ]; then
-                echo "Jenkins job failed. Exiting."
+            if [ "$http_code" -ne 200 ]; then
+              echo "Error fetching Jenkins job status. HTTP Response Code: $http_code"
+              echo "Response body: $body"
+              if [ $attempt -eq $max_attempts ]; then
+                echo "Max attempts reached. Exiting."
                 exit 1
               fi
-            done
+              continue
+            fi
 
-            if [ $attempt -eq $max_attempts ]; then
-              echo "Max attempts reached. Job did not complete successfully."
+            if ! job_status=$(echo "$body" | jq -r '.result'); then
+              echo "Error parsing JSON response. Raw response:"
+              echo "$body"
+              if [ $attempt -eq $max_attempts ]; then
+                echo "Max attempts reached. Exiting."
+                exit 1
+              fi
+              continue
+            fi
+
+            echo "Current Job Status: $job_status"
+
+            if [ "$job_status" = "FAILURE" ]; then
+              echo "Jenkins job failed. Exiting."
               exit 1
             fi
+          done
+
+          if [ $attempt -eq $max_attempts ]; then
+            echo "Max attempts reached. Job did not complete successfully."
+            exit 1
+          fi
 
   send_failure_notification:
     name: Send Failure Notification
     runs-on: ubuntu-latest
-    needs: build
+    needs:
+      [
+        dependabot,
+        lint,
+        build,
+        run-api,
+        run-web-and-test,
+        push_to_registry,
+        ZAP_Full_Scan,
+        ZAP_API_Scan,
+        trigger_jenkins,
+      ]
     if: ${{ failure() }}
     concurrency:
       group: send-failure-notification-${{ github.ref }}
@@ -220,7 +380,7 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
-          fetch-depth: 0  # Fetch all history
+          fetch-depth: 0 # Fetch all history
 
       - name: Download Error Files
         uses: actions/download-artifact@v3
@@ -275,7 +435,18 @@ jobs:
   send_success_notification:
     name: Send Success Notification
     runs-on: ubuntu-latest
-    needs: [lint, build, push_to_registry, trigger_jenkins_job]
+    needs:
+      [
+        dependabot,
+        lint,
+        build,
+        run-api,
+        run-web-and-test,
+        push_to_registry,
+        ZAP_Full_Scan,
+        ZAP_API_Scan,
+        trigger_jenkins,
+      ]
     if: ${{ success() }}
     concurrency:
       group: send-success-notification-${{ github.ref }}
@@ -284,7 +455,7 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
         with:
-          fetch-depth: 0  # Fetch all history
+          fetch-depth: 0 # Fetch all history
 
       - name: Get Commit Info
         id: commit_info
