testi

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -1,157 +1,159 @@
 name: commitlog
 
 on:
-  push:
-    branches:
-      - main
+ push:
+   branches:
+     - main
 
 jobs:
-  lint:
-    name: Lint Code Base
-    runs-on: ubuntu-latest
+ lint:
+   name: Lint Code Base
+   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+   steps:
+     - name: Checkout Code
+       uses: actions/checkout@v3
 
-      - name: Run Super-Linter
-        uses: github/super-linter@v4
-        env:
-          VALIDATE_ALL_CODEBASE: false
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+     - name: Run Super-Linter
+       uses: github/super-linter@v4
+       env:
+         VALIDATE_ALL_CODEBASE: false
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  build:
-    name: Check Code Quality
-    runs-on: ubuntu-latest
-    needs: lint
+ build:
+   name: Check Code Quality
+   runs-on: ubuntu-latest
+   needs: lint
 
-    outputs:
-      error_files: ${{ steps.determine_check_code_result.outputs.error_files }}
+   steps:
+     - name: Checkout Code
+       uses: actions/checkout@v3
 
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
+     - name: Set up Node.js
+       uses: actions/setup-node@v2
+       with:
+         node-version: '18'
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '18'
+     - name: Install dependencies
+       run: npm install
 
-      - name: Install dependencies
-        run: npm install
+     - name: Build project
+       id: build_step
+       run: |
+         npm run build 2> build_errors.log || true
+     - name: Determine check code result
+       id: determine_check_code_result
+       run: |
+         if grep -q "error" build_errors.log; then
+           echo "Check code failed"
+           ERROR_FILES=$(grep "error" build_errors.log | awk -F: '{print $1}' | sort | uniq | tr '\n' ' ')
+           echo "Error files: ${ERROR_FILES}"
+           echo "::set-output name=error_files::${ERROR_FILES}"
+           exit 1
+         else
+           echo "Check code succeeded"
+           echo "::set-output name=error_files::"
+         fi
+     - name: Upload Error Files
+       uses: actions/upload-artifact@v3
+       with:
+         name: error-files
+         path: build_errors.log
 
-      - name: Build project
-        id: build_step
-        run: |
-          npm run build 2> build_errors.log || true
-      - name: Determine check code result
-        id: determine_check_code_result
-        run: |
-          if grep -q "error" build_errors.log; then
-            echo "Check code failed"
-            ERROR_FILES=$(grep "error" build_errors.log | awk -F: '{print $1}' | sort | uniq | tr '\n' ' ')
-            echo "Error files: ${ERROR_FILES}"
-            echo "::set-output name=error_files::${ERROR_FILES}"
-            echo "${ERROR_FILES}" > error_files.log
-            exit 1
-          else
-            echo "Check code succeeded"
-            echo "::set-output name=error_files::"
-          fi
-      - name: Log Error Files
-        if: failure()
-        run: |
-          echo "Logged Error Files: ${{ steps.determine_check_code_result.outputs.error_files }}"
-          cat error_files.log
+ push_to_registry:
+   name: Push Docker image to Docker Hub
+   runs-on: ubuntu-latest
+   needs: build
 
-  push_to_registry:
-    name: Push Docker image to Docker Hub
-    runs-on: ubuntu-latest
-    needs: build
+   steps:
+     - name: Check out the repo
+       uses: actions/checkout@v3
 
-    steps:
-      - name: Check out the repo
-        uses: actions/checkout@v3
+     - name: Log in to Docker Hub
+       uses: docker/login-action@v2
+       with:
+         username: ${{ secrets.DOCKER_USERNAME }}
+         password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+     - name: Extract metadata for Docker
+       id: meta
+       uses: docker/metadata-action@v4
+       with:
+         images: krisneonploy/dockerbuild
 
-      - name: Extract metadata for Docker
-        id: meta
-        uses: docker/metadata-action@v4
-        with:
-          images: krisneonploy/dockerbuild
+     - name: Build and push Docker image
+       uses: docker/build-push-action@v4
+       with:
+         context: .
+         push: true
+         tags: ${{ steps.meta.outputs.tags }}
+         labels: ${{ steps.meta.outputs.labels }}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          push: true
-          tags: ${{ steps.meta.outputs.tags }}
-          labels: ${{ steps.meta.outputs.labels }}
+     - name: Create New Branch with Commit Hash
+       env:
+         GH_PAT: ${{ secrets.GH_PAT }}
+       run: |
+         git config user.name dornrock123
+         git config user.email krisd3214@gmail.com
+         COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+         NEW_BRANCH_NAME="log-$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-' | tr '[:punct:]' '-')"
+         git checkout -b $NEW_BRANCH_NAME
+         git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
 
-      - name: Create New Branch with Commit Hash
-        env:
-          GH_PAT: ${{ secrets.GH_PAT }}
-        run: |
-          git config user.name dornrock123
-          git config user.email krisd3214@gmail.com
-          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-          NEW_BRANCH_NAME="log-$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-' | tr '[:punct:]' '-')"
-          git checkout -b $NEW_BRANCH_NAME
-          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME
+ get_commit_author_email:
+   name: Get Commit Author Email
+   runs-on: ubuntu-latest
+   outputs:
+     commit_author_email: ${{ steps.get_commit_info.outputs.commit_author_email }}
+   steps:
+     - name: Checkout Code
+       uses: actions/checkout@v3
+       with:
+         fetch-depth: 2  # Fetch at least 2 commits to compare with previous commit
 
-  get_commit_author_email:
-    name: Get Commit Author Email
-    runs-on: ubuntu-latest
-    outputs:
-      commit_author_email: ${{ steps.get_commit_info.outputs.commit_author_email }}
-    steps:
-      - name: Checkout Code
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 2  # Fetch at least 2 commits to compare with previous commit
+     - name: Get Commit Info
+       id: get_commit_info
+       run: |
+         AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
+         echo "::set-output name=commit_author_email::${AUTHOR_EMAIL}"
 
-      - name: Get Commit Info
-        id: get_commit_info
-        run: |
-          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
-          echo "::set-output name=commit_author_email::${AUTHOR_EMAIL}"
+ send_notification:
+   name: Send Notification
+   runs-on: ubuntu-latest
+   needs: [lint, build, push_to_registry, get_commit_author_email]
+   if: ${{ failure() }}
+   steps:
 
-  send_notification:
-    name: Send Notification
-    runs-on: ubuntu-latest
-    needs: [lint, build, push_to_registry, get_commit_author_email]
-    if: ${{ failure() }}
-    steps:
+     - name: Checkout Code
+       uses: actions/checkout@v3
 
-      - name: Checkout Code
-        uses: actions/checkout@v3
+     - name: Download Error Files
+       uses: actions/download-artifact@v3
+       with:
+         name: error-files
 
-      - name: Read Error Files
-        id: read_error_files
-        run: |
-          echo "::set-output name=error_files::${ERROR_FILES}"
+     - name: Read Error Files
+       id: read_error_files
+       run: |
+         ERROR_FILES=$(cat error-files/build_errors.log)
+         echo "::set-output name=error_files::${ERROR_FILES}"
 
-      - name: Send email on failure
-        uses: dawidd6/action-send-mail@v3
-        with:
-          server_address: smtp.gmail.com
-          server_port: 587
-          username: ${{ secrets.GMAIL_USERNAME }}
-          password: ${{ secrets.GMAIL_APP_PASSWORD }}
-          subject: ${{ github.job }} job of ${{ github.repository }}
-          body: |
-            The following files caused errors during the build:
-            ${{ steps.read_error_files.outputs.error_files }}
-          to: ${{ needs.get_commit_author_email.outputs.commit_author_email }}
-          from: ${{ secrets.GMAIL_USERNAME }}
+     - name: Send email on failure
+       uses: dawidd6/action-send-mail@v3
+       with:
+         server_address: smtp.gmail.com
+         server_port: 587
+         username: ${{ secrets.GMAIL_USERNAME }}
+         password: ${{ secrets.GMAIL_APP_PASSWORD }}
+         subject: ${{ github.job }} job of ${{ github.repository }}
+         body: |
+           The following files caused errors during the build:
+           ${{ steps.read_error_files.outputs.error_files }}
+         to: ${{ needs.get_commit_author_email.outputs.commit_author_email }}
+         from: ${{ secrets.GMAIL_USERNAME }}
 
-      - name: Log Notification Data
-        if: ${{ always() }}
-        run: |
-          echo "Build step error files: ${{ steps.read_error_files.outputs.error_files }}"
-          echo "Commit author email: ${{ needs.get_commit_author_email.outputs.commit_author_email }}"
+     - name: Log Notification Data
+       if: ${{ always() }}
+       run: |
+         echo "Build step error files: ${{ steps.read_error_files.outputs.error_files }}"
+         echo "Commit author email: ${{ needs.get_commit_author_email.outputs.commit_author_email }}"
