dorn

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -128,12 +128,32 @@ jobs:
     name: Trigger Jenkins Job
     runs-on: ubuntu-latest
     needs: push_to_registry
+    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 
     steps:
       - name: Trigger Jenkins Job
         run: |
-          curl -X POST "https://2a7c-61-7-146-25.ngrok-free.app/job/dornny/build" \
-          --user "dornrock:1147d17fc8ec8e23ed131270370d186bf6"
+          echo "Triggering Jenkins job..."
+          response=$(curl -X POST "https://2a7c-61-7-146-25.ngrok-free.app/job/dornny/build" \
+          --user "dornrock:1147d17fc8ec8e23ed131270370d186bf6")
+          echo "Response from Jenkins: $response"
+
+      - name: Wait for Jenkins Job to Complete
+        run: |
+          echo "Waiting for Jenkins job to complete..."
+          JOB_STATUS="STARTED"
+          while [[ "$JOB_STATUS" != "SUCCESS" && "$JOB_STATUS" != "FAILURE" ]]; do
+            sleep 30  # รอ 30 วินาทีก่อนที่จะเช็คสถานะอีกครั้ง
+            JOB_STATUS=$(curl -s -u "dornrock:1147d17fc8ec8e23ed131270370d186bf6" "https://2a7c-61-7-146-25.ngrok-free.app/job/dornny/lastBuild/api/json" | jq -r '.result')
+            echo "Current Job Status: $JOB_STATUS"
+          done
+
+          if [[ "$JOB_STATUS" == "FAILURE" ]]; then
+            echo "Jenkins job failed!"
+            exit 1
+          else
+            echo "Jenkins job succeeded!"
+          fi
 
   send_failure_notification:
     name: Send Failure Notification
@@ -228,7 +248,7 @@ jobs:
           server_port: 587
           username: ${{ secrets.GMAIL_USERNAME }}
           password: ${{ secrets.GMAIL_APP_PASSWORD }}
-          subject: "Build Success for ${{ github.repository }}"
+          subject: "Build succeeded for ${{ github.repository }}"
           body: |
             Build succeeded for commit: ${{ github.sha }}
 
