tetg

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -42,7 +42,7 @@ jobs:
         run: |
           npm run build 2> build_errors.log
           exit_code=$?
-          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_OUTPUT
+          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
           exit $exit_code
 
       - name: Create Gist for Error Files
@@ -50,7 +50,8 @@ jobs:
         id: create_gist
         run: |
           if [[ "${{ steps.build.outputs.error_files_present }}" == "true" ]]; then
-            gist_response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            gist_response=$(curl -sSf \
+              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -X POST \
               -d @- \
               https://api.github.com/gists << EOF
@@ -66,10 +67,13 @@ jobs:
             EOF
             )
             gist_url=$(echo "$gist_response" | jq -r '.html_url')
-            echo "gist_url=$gist_url" >> $GITHUB_OUTPUT
+            echo "gist_url=$gist_url" >> $GITHUB_ENV
           else
-            echo "gist_url=" >> $GITHUB_OUTPUT
+            echo "gist_url=" >> $GITHUB_ENV
           fi
+          exit_code=$?
+          echo "error_files_present=$([[ $exit_code -ne 0 ]])" >> $GITHUB_ENV
+          exit $exit_code
 
       - name: Upload Error Files as Artifact
         if: ${{ steps.build.outputs.error_files_present == 'true' || always() }}
@@ -84,7 +88,6 @@ jobs:
     needs: build
 
     steps:
-
       - name: Check out the repo
         uses: actions/checkout@v3
 
@@ -142,7 +145,7 @@ jobs:
             changed_files=$(git diff --name-only HEAD~1 HEAD | tr '\n' '\n')
 
             error_paths=$(grep -o '/.*error' build_errors.log | sed 's/:.*//' | sort -u | tr '\n' ' ' | sed 's/ $//')
-            echo "error_paths=$error_paths" >> $GITHUB_OUTPUT
+            echo "error_paths=$error_paths" >> $GITHUB_ENV
 
             error_files_array=($(echo "$error_paths" | tr ' ' '\n'))
             non_error_files=""
@@ -158,13 +161,13 @@ jobs:
                     non_error_files+="$file "
                 fi
             done <<< "$changed_files"
-            echo "non_error_files=$non_error_files" >> $GITHUB_OUTPUT
+            echo "non_error_files=$non_error_files" >> $GITHUB_ENV
 
-            echo "commit_author_email=$commit_author_email" >> $GITHUB_OUTPUT
-            echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
+            echo "commit_author_email=$commit_author_email" >> $GITHUB_ENV
+            echo "changed_files=$changed_files" >> $GITHUB_ENV
 
             gist_url="${{ steps.create_gist.outputs.gist_url }}"
-            echo "gist_url=$gist_url" >> $GITHUB_OUTPUT
+            echo "gist_url=$gist_url" >> $GITHUB_ENV
 
       - name: Send email on failure
         uses: dawidd6/action-send-mail@v3
