test

diff --git a/.github/workflows/pushlog.yml b/.github/workflows/pushlog.yml
--- a/.github/workflows/pushlog.yml
+++ b/.github/workflows/pushlog.yml
@@ -25,9 +25,6 @@ jobs:
     runs-on: ubuntu-latest
     needs: lint
 
-    env:
-      CHECK_CODE_RESULT: ''
-
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
@@ -42,8 +39,7 @@ jobs:
 
       - name: Build project
         run: |
-          npm run build || echo "::set-env name=BUILD_ERROR::true"
-      
+          npm run build || echo "BUILD_ERROR=true" >> $GITHUB_ENV
 
   push_to_registry:
     name: Push Docker image to Docker Hub
@@ -103,25 +99,28 @@ jobs:
   send_notification:
     name: Send Notification
     runs-on: ubuntu-latest
-    needs: [lint, build]
+    needs: [lint, build, push_to_registry, get_commit_author_email]
 
-    if: ${{ env.BUILD_ERROR == 'true' }}
-  
+    if: ${{ success() || failure() }}
+
     steps:
-    - name: Send email on build failure
-      uses: dawidd6/action-send-mail@v3
-      with:
-        server_address: smtp.gmail.com
-        server_port: 587
-        username: ${{ secrets.GMAIL_USERNAME }}
-        password: ${{ secrets.GMAIL_APP_PASSWORD }}
-        subject: GitHub Action Build Failure Notification
-        body: |
-          The build of the GitHub Action workflow has failed. 
-          Details:
-          - Repository: ${{ github.repository }}
-          - Error message: ${{ job.status }}
-          - Commit SHA: ${{ github.sha }}
-          - Action URL: ${{ github.run_url }}
-        to: ${{ secrets.NOTIFICATION_EMAIL }}
-        from: ${{ secrets.GMAIL_USERNAME }}
+      - name: Send email on failure
+        if: failure()
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          username: ${{ secrets.GMAIL_USERNAME }}
+          password: ${{ secrets.GMAIL_APP_PASSWORD }}
+          subject: GitHub Action Failure Notification
+          body: |
+            The build of the GitHub Action workflow has failed. 
+            Details:
+            - Commit message: ${{ github.event.head_commit.message }}
+            - Repository: ${{ github.repository }}
+          to: ${{ needs.get_commit_author_email.outputs.commit_author_email }}
+          from: ${{ secrets.GMAIL_USERNAME }}
+
+      - name: Send email on success
+        if: success()
+        run: echo "All jobs in the GitHub Action workflow have succeeded."
